name: Bug Report
description: Use this form to report a bug with ZalcBot.
labels: [bug]
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      placeholder: A short title for the bug
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to make it happen
      description: Write step-by-step how to make the bug happen again
      placeholder: |
        1. Go to Twitch chat
        2. Type !command
        3. Bot crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened?
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Where did this happen?
      options:
        - Discord
        - Twitch
        - Web Panel
        - Spotify
        - Other
    validations:
      required: true
